#!/usr/bin/env python3
"""
LANDSCAPE ENGINE: Pythagorean Triple Tree × Inverse Stereographic Projection

Research Program: Using geometric "landscapes" generated by inverse stereographic
projection to guide heuristic search through the Berggren tree for integer factoring.

Core Idea:
  Every primitive Pythagorean triple (a,b,c) maps to a rational point (a/c, b/c) on S¹.
  Under stereographic projection, this corresponds to a parameter t = a/(b+c).
  The "landscape" is the local geometry of S¹ near this point, including:
    - Conformal factor (how distances are distorted)
    - Angular position (where on the circle)
    - Curvature of the energy surface for factoring
    - Relationship between parent/child landscapes

The Berggren tree generates ALL primitive Pythagorean triples. If N = p*q,
then N appears as the odd leg of some primitive triple (or a multiple thereof),
and finding that triple gives the factorization.
"""

import numpy as np
from fractions import Fraction
from typing import Tuple, List, Dict, Optional
import json

# ============================================================
# §1: CORE MATHEMATICAL OBJECTS
# ============================================================

def inv_stereo(t: float) -> Tuple[float, float]:
    """Inverse stereographic projection: ℝ → S¹
    σ(t) = (2t/(1+t²), (1-t²)/(1+t²))
    """
    d = 1 + t**2
    return (2*t/d, (1 - t**2)/d)

def stereo_forward(x: float, y: float) -> float:
    """Forward stereographic projection: S¹ → ℝ
    Given (x,y) on S¹ with y ≠ -1, returns t = x/(1+y)
    """
    if abs(1 + y) < 1e-15:
        return float('inf')
    return x / (1 + y)

def conformal_factor(t: float) -> float:
    """The conformal factor of inverse stereographic projection at parameter t.
    λ(t) = 2/(1+t²)
    This measures how much distances are stretched/compressed.
    """
    return 2.0 / (1 + t**2)

def euclid_params(a: int, b: int, c: int) -> Tuple[int, int]:
    """Extract Euclid parameters (m,n) from a primitive triple (a,b,c).
    If a is odd: a = m²-n², b = 2mn, c = m²+n²
    So m² = (a+c)/2, n² = (c-a)/2, and m,n can be recovered.
    If b is odd, swap a,b first.
    """
    if a % 2 == 0:
        a, b = b, a
    m_sq = (a + c) // 2
    n_sq = (c - a) // 2
    m = int(round(m_sq**0.5))
    n = int(round(n_sq**0.5))
    if m*m == m_sq and n*n == n_sq:
        return (m, n)
    return (0, 0)  # Not a valid triple or not primitive

def stereo_param_from_triple(a: int, b: int, c: int) -> float:
    """Get stereographic parameter t for a Pythagorean triple.
    The point on S¹ is (a/c, b/c), so t = (a/c)/(1 + b/c) = a/(c+b).
    Alternatively, if we use Euclid params: t = n/m.
    """
    if c + b == 0:
        return float('inf')
    return a / (c + b)

def stereo_param_rational(a: int, b: int, c: int) -> Fraction:
    """Exact rational stereographic parameter."""
    return Fraction(a, c + b)

# ============================================================
# §2: BERGGREN TREE OPERATIONS
# ============================================================

def berggren_children(a: int, b: int, c: int) -> List[Tuple[int, int, int]]:
    """Generate the three children of (a,b,c) in the Berggren tree.
    M₁: (a - 2b + 2c, 2a - b + 2c, 2a - 2b + 3c)
    M₂: (a + 2b + 2c, 2a + b + 2c, 2a + 2b + 3c)
    M₃: (-a + 2b + 2c, -2a + b + 2c, -2a + 2b + 3c)
    """
    c1 = (a - 2*b + 2*c, 2*a - b + 2*c, 2*a - 2*b + 3*c)
    c2 = (a + 2*b + 2*c, 2*a + b + 2*c, 2*a + 2*b + 3*c)
    c3 = (-a + 2*b + 2*c, -2*a + b + 2*c, -2*a + 2*b + 3*c)
    return [c1, c2, c3]

def berggren_parent(a: int, b: int, c: int) -> Optional[Tuple[int, int, int]]:
    """Find the parent of (a,b,c) in the Berggren tree.
    Try all three inverse matrices and return the one giving positive components.
    B₁⁻¹: (a + 2b - 2c, -2a - b + 2c, -2a - 2b + 3c)
    B₂⁻¹: (a + 2b - 2c, 2a + b - 2c, -2a - 2b + 3c)  -- note: same first component
    B₃⁻¹: (-a - 2b + 2c, 2a + b - 2c, -2a - 2b + 3c)
    """
    candidates = [
        (a + 2*b - 2*c, -2*a - b + 2*c, -2*a - 2*b + 3*c),  # B₁⁻¹
        (a + 2*b - 2*c, 2*a + b - 2*c, -2*a - 2*b + 3*c),    # B₂⁻¹
        (-a - 2*b + 2*c, 2*a + b - 2*c, -2*a - 2*b + 3*c),   # B₃⁻¹
    ]
    for pa, pb, pc in candidates:
        if pa > 0 and pb > 0 and pc > 0 and pa*pa + pb*pb == pc*pc:
            return (pa, pb, pc)
    return None

def tree_path_to_triple(path: str) -> Tuple[int, int, int]:
    """Convert a path string like 'LMR' to a Berggren triple.
    L = left (M₁), M = mid (M₂), R = right (M₃).
    """
    a, b, c = 3, 4, 5
    for ch in path:
        children = berggren_children(a, b, c)
        if ch == 'L':
            a, b, c = children[0]
        elif ch == 'M':
            a, b, c = children[1]
        elif ch == 'R':
            a, b, c = children[2]
    return (a, b, c)

def triple_to_path(a: int, b: int, c: int) -> str:
    """Find the Berggren tree path from root to (a,b,c)."""
    path = []
    while (a, b, c) != (3, 4, 5):
        parent = berggren_parent(a, b, c)
        if parent is None:
            return "NOT_FOUND"
        pa, pb, pc = parent
        children = berggren_children(pa, pb, pc)
        if (a, b, c) == children[0]:
            path.append('L')
        elif (a, b, c) == children[1]:
            path.append('M')
        elif (a, b, c) == children[2]:
            path.append('R')
        else:
            return "ERROR"
        a, b, c = pa, pb, pc
    return ''.join(reversed(path))

# ============================================================
# §3: LANDSCAPE GENERATION
# ============================================================

class Landscape:
    """The stereographic landscape of a Pythagorean triple.
    
    A "landscape" captures the geometric structure around a triple's
    position on S¹ under inverse stereographic projection.
    """
    def __init__(self, a: int, b: int, c: int):
        self.a, self.b, self.c = a, b, c
        self.t = stereo_param_from_triple(a, b, c)
        self.t_exact = stereo_param_rational(a, b, c)
        self.circle_point = (a/c, b/c)
        self.angle = np.arctan2(b, a)  # angle on circle
        self.conformal = conformal_factor(self.t)
        
        # Euclid parameters
        self.m, self.n = euclid_params(a, b, c)
        
        # Factoring information from the odd leg
        odd_leg = a if a % 2 == 1 else b
        if self.m > 0 and self.n > 0:
            self.factor1 = self.m - self.n  # (m-n)
            self.factor2 = self.m + self.n  # (m+n)
            self.factored_value = self.factor1 * self.factor2  # = odd leg
        else:
            self.factor1 = self.factor2 = self.factored_value = 0
        
        # Energy surface: E(s) = (target - σ(s))² evaluated near t
        # Local curvature of the energy surface
        self.energy_curvature = self._compute_curvature()
    
    def _compute_curvature(self) -> float:
        """Compute the curvature of the stereographic image curve at parameter t."""
        # For σ(t), the curvature κ of the circle at the image point is always 1
        # (it's a unit circle). But the "effective curvature" in the t-parameter
        # is κ_eff = κ * |σ'(t)| = conformal_factor(t)
        return self.conformal
    
    def local_density(self, window: float = 0.1) -> float:
        """How many rational points with small denominator are near this t."""
        count = 0
        for p in range(1, 50):
            for q in range(1, 50):
                if abs(Fraction(p, q) - self.t_exact) < Fraction(1, 100):
                    count += 1
        return count
    
    def distance_to(self, other: 'Landscape') -> Dict[str, float]:
        """Multiple distance metrics between two landscapes."""
        # Angular distance on S¹
        ang_dist = abs(self.angle - other.angle)
        ang_dist = min(ang_dist, 2*np.pi - ang_dist)
        
        # Stereographic distance (on ℝ)
        stereo_dist = abs(self.t - other.t)
        
        # Conformal ratio (how different the local geometries are)
        conf_ratio = self.conformal / other.conformal if other.conformal > 0 else float('inf')
        
        # Hyperbolic distance (using the Poincaré model via Cayley transform)
        # d_hyp = |log(t₁/t₂)| when both t > 0
        if self.t > 0 and other.t > 0:
            hyp_dist = abs(np.log(self.t / other.t))
        else:
            hyp_dist = float('inf')
        
        return {
            'angular': ang_dist,
            'stereographic': stereo_dist,
            'conformal_ratio': conf_ratio,
            'hyperbolic': hyp_dist
        }
    
    def __repr__(self):
        return (f"Landscape(({self.a},{self.b},{self.c}), t={float(self.t_exact):.6f}, "
                f"θ={np.degrees(self.angle):.2f}°, λ={self.conformal:.6f}, "
                f"Euclid=({self.m},{self.n}))")

def generate_landscape_report(a: int, b: int, c: int, depth: int = 0) -> Dict:
    """Generate a comprehensive landscape report for a triple."""
    L = Landscape(a, b, c)
    
    report = {
        'triple': (a, b, c),
        'depth': depth,
        'stereo_param': float(L.t_exact),
        'angle_deg': np.degrees(L.angle),
        'conformal_factor': L.conformal,
        'circle_point': L.circle_point,
        'euclid_params': (L.m, L.n),
        'factorization': f"{L.factored_value} = {L.factor1} × {L.factor2}" if L.factor1 > 0 else "N/A",
    }
    
    # Children landscapes
    children = berggren_children(a, b, c)
    child_landscapes = []
    for i, (ca, cb, cc) in enumerate(children):
        cL = Landscape(ca, cb, cc)
        child_landscapes.append({
            'branch': ['M₁ (Left)', 'M₂ (Mid)', 'M₃ (Right)'][i],
            'triple': (ca, cb, cc),
            'stereo_param': float(cL.t_exact),
            'angle_deg': np.degrees(cL.angle),
            'conformal_factor': cL.conformal,
            'distance_from_parent': L.distance_to(cL),
            'euclid_params': (cL.m, cL.n),
            'factorization': f"{cL.factored_value} = {cL.factor1} × {cL.factor2}" if cL.factor1 > 0 else "N/A",
        })
    report['children'] = child_landscapes
    
    return report

# ============================================================
# §4: FACTORING VIA LANDSCAPE-GUIDED SEARCH
# ============================================================

def encode_factoring_target(N: int) -> Dict:
    """Given N = p*q (odd composite), find the target Pythagorean triple(s).
    
    Method: N as an odd leg means N = m² - n² = (m-n)(m+n).
    For each factorization N = d₁ * d₂ with d₁ < d₂ and d₁ ≡ d₂ (mod 2):
      m = (d₁ + d₂)/2, n = (d₂ - d₁)/2
      Triple: (N, 2mn, m²+n²)
    
    The TARGET stereographic parameter is t = n/m = (d₂-d₁)/(d₁+d₂)
    """
    targets = []
    for d1 in range(1, int(N**0.5) + 1):
        if N % d1 == 0:
            d2 = N // d1
            if d1 < d2 and (d1 % 2) == (d2 % 2):
                m = (d1 + d2) // 2
                n = (d2 - d1) // 2
                from math import gcd
                g = gcd(m, n)
                if g == 1 and (m - n) % 2 == 1:  # primitive
                    a = m*m - n*n
                    b = 2*m*n
                    c = m*m + n*n
                    t_target = n / m
                    targets.append({
                        'N': N,
                        'factors': (d1, d2),
                        'm': m, 'n': n,
                        'triple': (a, b, c),
                        't_target': t_target,
                        'angle': np.degrees(np.arctan2(b, a)),
                    })
    return targets

def landscape_guided_search(N: int, max_depth: int = 20, verbose: bool = True) -> Dict:
    """
    Search the Berggren tree for a triple whose odd leg divides N,
    using landscape comparison as a heuristic.
    
    HEURISTIC: At each node, compute the stereographic parameter t for each child.
    Compare to the target parameter t_target = n/m where N = (m-n)(m+n).
    Descend to the child whose t is closest to t_target.
    
    The landscape comparison uses angular distance on S¹, which is the
    natural metric for comparing Pythagorean triples.
    """
    targets = encode_factoring_target(N)
    if not targets:
        return {'success': False, 'reason': 'No valid target triples found'}
    
    # Use the first target (smallest factor pair)
    target = targets[0]
    t_target = target['t_target']
    target_angle = np.radians(target['angle'])
    
    if verbose:
        print(f"\n{'='*70}")
        print(f"LANDSCAPE-GUIDED FACTORING: N = {N}")
        print(f"Target: t* = {t_target:.10f} (angle = {target['angle']:.4f}°)")
        print(f"Target triple: {target['triple']}")
        print(f"Target factors: {N} = {target['factors'][0]} × {target['factors'][1]}")
        print(f"{'='*70}")
    
    # Start at root
    a, b, c = 3, 4, 5
    path = []
    visited = [(a, b, c)]
    
    for depth in range(max_depth):
        L_current = Landscape(a, b, c)
        
        # Check if current node gives a factorization
        odd_leg = a if a % 2 == 1 else b
        if odd_leg > 1 and N % odd_leg == 0 and odd_leg < N:
            factor = odd_leg
            cofactor = N // factor
            if verbose:
                print(f"\n✅ FOUND at depth {depth}: {N} = {factor} × {cofactor}")
                print(f"   Triple: ({a}, {b}, {c})")
                print(f"   Path: {''.join(path)}")
            return {
                'success': True,
                'depth': depth,
                'triple': (a, b, c),
                'factor': factor,
                'cofactor': cofactor,
                'path': ''.join(path),
            }
        
        # Generate children landscapes
        children = berggren_children(a, b, c)
        child_landscapes = []
        for i, (ca, cb, cc) in enumerate(children):
            cL = Landscape(ca, cb, cc)
            # Distance to target
            ang_dist = abs(cL.angle - target_angle)
            ang_dist = min(ang_dist, 2*np.pi - ang_dist)
            stereo_dist = abs(cL.t - t_target)
            
            child_landscapes.append({
                'index': i,
                'triple': (ca, cb, cc),
                'angle': cL.angle,
                'stereo_param': cL.t,
                'angular_dist': ang_dist,
                'stereo_dist': stereo_dist,
                'conformal': cL.conformal,
            })
        
        # HEURISTIC: Choose the child with smallest angular distance to target
        best = min(child_landscapes, key=lambda x: x['angular_dist'])
        
        if verbose:
            print(f"\nDepth {depth}: ({a},{b},{c}), t={L_current.t:.6f}, θ={np.degrees(L_current.angle):.2f}°")
            for cl in child_landscapes:
                marker = " ← BEST" if cl['index'] == best['index'] else ""
                branch = ['L','M','R'][cl['index']]
                print(f"  {branch}: {cl['triple']}, t={cl['stereo_param']:.6f}, "
                      f"Δθ={np.degrees(cl['angular_dist']):.4f}°, "
                      f"Δt={cl['stereo_dist']:.8f}{marker}")
        
        a, b, c = best['triple']
        path.append(['L','M','R'][best['index']])
        visited.append((a, b, c))
    
    return {'success': False, 'reason': 'Max depth reached', 'path': ''.join(path)}

# ============================================================
# §5: LANDSCAPE FITTING — HOW PARENT/CHILD LANDSCAPES RELATE
# ============================================================

def analyze_landscape_transitions(max_depth: int = 3):
    """Analyze how landscapes transform from parent to child.
    
    Key questions:
    1. How does the stereographic parameter t change across generations?
    2. Is there a pattern in the conformal factor ratios?
    3. How do the angular separations between children vary?
    4. Can we predict which subtree contains a target based on the parent landscape?
    """
    print("\n" + "="*70)
    print("LANDSCAPE TRANSITION ANALYSIS")
    print("="*70)
    
    # Generate tree to specified depth
    def explore(a, b, c, depth, path=""):
        L = Landscape(a, b, c)
        children = berggren_children(a, b, c)
        
        print(f"\n{'  '*depth}Node: ({a},{b},{c}) [path={path or 'root'}]")
        print(f"{'  '*depth}  t = {L.t:.8f}, θ = {np.degrees(L.angle):.4f}°, λ = {L.conformal:.8f}")
        print(f"{'  '*depth}  Euclid: m={L.m}, n={L.n}")
        if L.factor1 > 0:
            print(f"{'  '*depth}  Factorization: {L.factored_value} = {L.factor1} × {L.factor2}")
        
        if depth < max_depth:
            child_params = []
            for i, (ca, cb, cc) in enumerate(children):
                branch = ['L','M','R'][i]
                cL = Landscape(ca, cb, cc)
                child_params.append(cL.t)
                
                # Analyze the transition
                t_ratio = cL.t / L.t if L.t != 0 else float('inf')
                conf_ratio = cL.conformal / L.conformal
                ang_shift = np.degrees(cL.angle - L.angle)
                
                print(f"{'  '*depth}  → {branch}: ({ca},{cb},{cc})")
                print(f"{'  '*depth}      t_ratio={t_ratio:.6f}, conf_ratio={conf_ratio:.8f}, Δθ={ang_shift:.4f}°")
                
                explore(ca, cb, cc, depth + 1, path + branch)
            
            # Angular separation between children
            if len(child_params) == 3:
                print(f"{'  '*depth}  Children t-spread: [{min(child_params):.6f}, {max(child_params):.6f}]")
                print(f"{'  '*depth}  Children t-range: {max(child_params) - min(child_params):.6f}")
    
    explore(3, 4, 5, 0)

def landscape_parameter_evolution():
    """Track how the stereographic parameter t evolves along different paths."""
    print("\n" + "="*70)
    print("STEREOGRAPHIC PARAMETER EVOLUTION")
    print("="*70)
    
    paths = {
        'All Left (LLL...)': 'LLLLLL',
        'All Mid (MMM...)': 'MMMMMM',
        'All Right (RRR...)': 'RRRRRR',
        'Zigzag (LRLRLR)': 'LRLRLR',
        'Spiral (LMRLMR)': 'LMRLMR',
    }
    
    for name, path in paths.items():
        print(f"\n--- {name}: {path} ---")
        a, b, c = 3, 4, 5
        print(f"  depth 0: ({a},{b},{c}), t={stereo_param_from_triple(a,b,c):.8f}")
        
        for i, ch in enumerate(path):
            children = berggren_children(a, b, c)
            if ch == 'L':
                a, b, c = children[0]
            elif ch == 'M':
                a, b, c = children[1]
            else:
                a, b, c = children[2]
            
            L = Landscape(a, b, c)
            print(f"  depth {i+1}: ({a},{b},{c}), t={L.t:.8f}, θ={np.degrees(L.angle):.2f}°, "
                  f"λ={L.conformal:.8f}, odd_leg_factors={L.factor1}×{L.factor2}")

# ============================================================
# §6: HYPOTHESIS TESTING
# ============================================================

def test_angular_monotonicity():
    """HYPOTHESIS: Along the 'correct' path to a target, angular distance 
    to the target decreases monotonically.
    
    Test: For several factoring targets, trace the correct path and check
    if angular distance decreases at every step.
    """
    print("\n" + "="*70)
    print("HYPOTHESIS TEST: Angular Monotonicity Along Correct Path")
    print("="*70)
    
    test_cases = [15, 21, 35, 77, 143, 221, 323, 437]
    
    for N in test_cases:
        targets = encode_factoring_target(N)
        if not targets:
            continue
        
        target = targets[0]
        target_triple = target['triple']
        target_angle = np.radians(target['angle'])
        
        # Find the path to the target
        path = triple_to_path(*target_triple)
        if path == "NOT_FOUND":
            print(f"  N={N}: path not found")
            continue
        
        # Trace the path and record angular distances
        a, b, c = 3, 4, 5
        distances = []
        L = Landscape(a, b, c)
        ang_dist = abs(L.angle - target_angle)
        ang_dist = min(ang_dist, 2*np.pi - ang_dist)
        distances.append(ang_dist)
        
        for ch in path:
            children = berggren_children(a, b, c)
            if ch == 'L':
                a, b, c = children[0]
            elif ch == 'M':
                a, b, c = children[1]
            else:
                a, b, c = children[2]
            L = Landscape(a, b, c)
            ang_dist = abs(L.angle - target_angle)
            ang_dist = min(ang_dist, 2*np.pi - ang_dist)
            distances.append(ang_dist)
        
        monotone = all(distances[i] >= distances[i+1] for i in range(len(distances)-1))
        
        print(f"  N={N}: factors={target['factors']}, path={path}, "
              f"monotone={'✅ YES' if monotone else '❌ NO'}")
        print(f"    distances: {[f'{d:.6f}' for d in distances]}")

def test_landscape_heuristic_accuracy():
    """Test: Does the angular-distance heuristic choose the correct branch
    at each step along the path to a target?
    """
    print("\n" + "="*70)
    print("HYPOTHESIS TEST: Landscape Heuristic Branch Selection Accuracy")
    print("="*70)
    
    test_cases = [15, 21, 33, 35, 55, 65, 77, 91, 119, 143, 187, 221]
    
    for N in test_cases:
        targets = encode_factoring_target(N)
        if not targets:
            continue
        
        target = targets[0]
        target_triple = target['triple']
        target_angle = np.radians(target['angle'])
        t_target = target['t_target']
        
        path = triple_to_path(*target_triple)
        if path == "NOT_FOUND" or path == "":
            continue
        
        correct_choices = 0
        total_choices = len(path)
        
        a, b, c = 3, 4, 5
        for step, correct_ch in enumerate(path):
            children = berggren_children(a, b, c)
            
            # Heuristic: choose child with closest angle
            best_idx = -1
            best_dist = float('inf')
            for i, (ca, cb, cc) in enumerate(children):
                cL = Landscape(ca, cb, cc)
                ang_dist = abs(cL.angle - target_angle)
                ang_dist = min(ang_dist, 2*np.pi - ang_dist)
                if ang_dist < best_dist:
                    best_dist = ang_dist
                    best_idx = i
            
            heuristic_choice = ['L','M','R'][best_idx]
            if heuristic_choice == correct_ch:
                correct_choices += 1
            
            # Follow correct path
            if correct_ch == 'L':
                a, b, c = children[0]
            elif correct_ch == 'M':
                a, b, c = children[1]
            else:
                a, b, c = children[2]
        
        accuracy = correct_choices / total_choices if total_choices > 0 else 0
        print(f"  N={N}: path={path}, accuracy={accuracy:.0%} ({correct_choices}/{total_choices})")

def test_conformal_factor_as_signal():
    """HYPOTHESIS: The conformal factor ratio between parent and child
    contains information about which subtree leads to the target.
    """
    print("\n" + "="*70)
    print("HYPOTHESIS TEST: Conformal Factor as Navigation Signal")
    print("="*70)
    
    test_triples = [
        (3, 4, 5),
        (5, 12, 13),
        (21, 20, 29),
        (15, 8, 17),
        (7, 24, 25),
    ]
    
    for a, b, c in test_triples:
        L_parent = Landscape(a, b, c)
        children = berggren_children(a, b, c)
        
        print(f"\n  Parent: ({a},{b},{c}), λ={L_parent.conformal:.8f}")
        for i, (ca, cb, cc) in enumerate(children):
            cL = Landscape(ca, cb, cc)
            ratio = cL.conformal / L_parent.conformal
            branch = ['L','M','R'][i]
            print(f"    {branch}: ({ca},{cb},{cc}), λ={cL.conformal:.8f}, "
                  f"ratio={ratio:.8f}, Δλ={cL.conformal - L_parent.conformal:.8f}")

# ============================================================
# §7: ADVANCED LANDSCAPE METRICS
# ============================================================

def compute_landscape_signature(a: int, b: int, c: int) -> Dict:
    """Compute a rich signature for navigation heuristics.
    
    The signature includes:
    - Stereographic parameter t and its continued fraction expansion
    - Conformal factor and its logarithm
    - Angle on S¹ and angular velocity (rate of change per tree step)
    - Hyperbolic distance from root
    - "Factoring energy" — how close the odd leg is to being highly composite
    """
    L = Landscape(a, b, c)
    
    # Continued fraction expansion of t
    def continued_fraction(x, max_terms=10):
        cf = []
        for _ in range(max_terms):
            if abs(x - round(x)) < 1e-12:
                cf.append(int(round(x)))
                break
            cf.append(int(x))
            x = 1.0 / (x - int(x))
        return cf
    
    cf = continued_fraction(L.t) if L.t > 0 else [0]
    
    # Factoring energy: sum of squared differences from nearest primes
    odd_leg = a if a % 2 == 1 else b
    
    # Number of divisors of odd leg (rough measure of factoring utility)
    def count_divisors(n):
        n = abs(n)
        if n == 0:
            return 0
        count = 0
        for d in range(1, int(n**0.5) + 1):
            if n % d == 0:
                count += 2 if d * d != n else 1
        return count
    
    return {
        'triple': (a, b, c),
        't': L.t,
        'cf': cf,
        'conformal': L.conformal,
        'log_conformal': np.log(L.conformal) if L.conformal > 0 else float('-inf'),
        'angle': L.angle,
        'euclid': (L.m, L.n),
        'odd_leg': odd_leg,
        'odd_leg_divisors': count_divisors(odd_leg),
        'hyp_dist_from_root': abs(np.log(L.t / stereo_param_from_triple(3,4,5))) if L.t > 0 else float('inf'),
    }

def multi_metric_search(N: int, max_depth: int = 25, verbose: bool = True) -> Dict:
    """
    Enhanced search using multiple landscape metrics simultaneously.
    
    Combines:
    1. Angular distance (primary)
    2. Stereographic distance
    3. Conformal factor matching
    4. Continued fraction prefix matching
    
    Weighted combination to select the best child at each step.
    """
    targets = encode_factoring_target(N)
    if not targets:
        return {'success': False}
    
    target = targets[0]
    t_target = target['t_target']
    target_angle = np.radians(target['angle'])
    target_sig = compute_landscape_signature(*target['triple'])
    target_cf = target_sig['cf']
    
    if verbose:
        print(f"\n{'='*70}")
        print(f"MULTI-METRIC LANDSCAPE SEARCH: N = {N}")
        print(f"Target: t* = {t_target:.10f}")
        print(f"Target CF: {target_cf}")
        print(f"{'='*70}")
    
    a, b, c = 3, 4, 5
    path = []
    
    for depth in range(max_depth):
        # Check current node
        odd_leg = a if a % 2 == 1 else b
        if odd_leg > 1 and N % odd_leg == 0 and odd_leg < N:
            if verbose:
                print(f"\n✅ FOUND at depth {depth}: {N} = {odd_leg} × {N//odd_leg}")
            return {'success': True, 'depth': depth, 'path': ''.join(path),
                    'factor': odd_leg}
        
        children = berggren_children(a, b, c)
        
        scores = []
        for i, (ca, cb, cc) in enumerate(children):
            cL = Landscape(ca, cb, cc)
            sig = compute_landscape_signature(ca, cb, cc)
            
            # Metric 1: Angular distance
            ang_dist = abs(cL.angle - target_angle)
            ang_dist = min(ang_dist, 2*np.pi - ang_dist)
            
            # Metric 2: Stereographic distance
            stereo_dist = abs(cL.t - t_target)
            
            # Metric 3: Continued fraction prefix match length
            cf = sig['cf']
            cf_match = 0
            for j in range(min(len(cf), len(target_cf))):
                if cf[j] == target_cf[j]:
                    cf_match += 1
                else:
                    break
            
            # Metric 4: Log-conformal distance
            log_conf_dist = abs(sig['log_conformal'] - target_sig['log_conformal'])
            
            # Combined score (lower is better)
            score = (0.4 * ang_dist + 
                     0.3 * stereo_dist + 
                     0.2 * (10.0 / (cf_match + 1)) +
                     0.1 * log_conf_dist)
            
            scores.append((score, i))
        
        best_score, best_idx = min(scores)
        
        if verbose and depth < 10:
            print(f"  d={depth}: ({a},{b},{c}) → {['L','M','R'][best_idx]} (score={best_score:.6f})")
        
        a, b, c = children[best_idx]
        path.append(['L','M','R'][best_idx])
    
    return {'success': False, 'path': ''.join(path)}

# ============================================================
# §8: BATCH EXPERIMENTS
# ============================================================

def run_factoring_experiments():
    """Run factoring experiments on a range of semiprimes."""
    print("\n" + "="*70)
    print("FACTORING EXPERIMENTS: Landscape-Guided Search")
    print("="*70)
    
    # Test semiprimes (p * q)
    semiprimes = [
        (3, 5, 15),
        (3, 7, 21),
        (5, 7, 35),
        (3, 11, 33),
        (7, 11, 77),
        (11, 13, 143),
        (13, 17, 221),
        (17, 19, 323),
        (23, 29, 667),
        (31, 37, 1147),
        (41, 43, 1763),
        (53, 59, 3127),
        (71, 73, 5183),
        (97, 101, 9797),
        (127, 131, 16637),
    ]
    
    results = []
    for p, q, N in semiprimes:
        result = landscape_guided_search(N, max_depth=30, verbose=False)
        status = "✅" if result.get('success') else "❌"
        depth = result.get('depth', '—')
        path = result.get('path', '—')
        print(f"  {status} N={N:>6} = {p:>3} × {q:>3} | depth={str(depth):>3} | path={path[:20]}")
        results.append(result)
    
    successes = sum(1 for r in results if r.get('success'))
    print(f"\n  Success rate: {successes}/{len(results)}")
    return results

def compare_search_methods(N: int):
    """Compare angular heuristic vs multi-metric heuristic."""
    print(f"\n{'='*70}")
    print(f"SEARCH METHOD COMPARISON: N = {N}")
    print(f"{'='*70}")
    
    r1 = landscape_guided_search(N, max_depth=30, verbose=False)
    r2 = multi_metric_search(N, max_depth=30, verbose=False)
    
    print(f"  Angular heuristic:     {'✅' if r1.get('success') else '❌'} depth={r1.get('depth','—')}")
    print(f"  Multi-metric heuristic: {'✅' if r2.get('success') else '❌'} depth={r2.get('depth','—')}")

# ============================================================
# MAIN EXECUTION
# ============================================================

if __name__ == "__main__":
    print("╔" + "═"*68 + "╗")
    print("║  PYTHAGOREAN LANDSCAPE ENGINE                                      ║")
    print("║  Factoring via Berggren Tree × Inverse Stereographic Projection    ║")
    print("╚" + "═"*68 + "╝")
    
    # §A: Generate root landscape
    print("\n" + "="*70)
    print("§A: ROOT NODE LANDSCAPE")
    print("="*70)
    root_report = generate_landscape_report(3, 4, 5)
    print(json.dumps(root_report, indent=2, default=str))
    
    # §B: Landscape transition analysis
    analyze_landscape_transitions(max_depth=2)
    
    # §C: Parameter evolution along different paths
    landscape_parameter_evolution()
    
    # §D: Hypothesis testing
    test_angular_monotonicity()
    test_landscape_heuristic_accuracy()
    test_conformal_factor_as_signal()
    
    # §E: Factoring experiments
    run_factoring_experiments()
    
    # §F: Method comparison
    for N in [35, 77, 143, 323, 667]:
        compare_search_methods(N)
    
    print("\n\n✅ All experiments complete.")
